# Variable of TACACS+ server groups #
tacacs_svr_group:
  - name: TAC-GROUP1          #<-- Logical Name of the TACACS+ server group
    source_interface: vlan30  #<-- Replace with actual source interface for TACACS+ server communication
    server_1: tacacs1         #<-- Reference to the primary TACACS+ server defined in group_vars/all.yml
    server_2: tacacs2         #<-- Reference to the secondary TACACS+ server defined in group_vars/all.yml

# Variable of NTP source interface #
ntp_src_intf: vlan30

# SNMP source interface for access switches
snmp_trap_source: vlan30
snmp_inform_source: vlan30